language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - gunicorn app.main:app
  - coverage run -m pytest tests
  - pylint app
after_script:
  - coveralls
