language: python
python:
  - "3.8"
services:
  - mysql
env:
  global:
    - DB_NAME=my_stocks_db
    - DB_USER=root
    - DB_PASSWORD=password
    - DB_HOST=localhost
    - DB_URL=mysql://$DB_USER:$DB_PASSWORD@$DB_HOST/$DB_NAME
before_install:
  - echo $DB_USER
  - echo $DB_PASSWORD
  - echo $DB_HOST
install:
  - pip install -r requirements.txt

before_script:
  - mysql -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS my_stocks_db;'
  - gunicorn -w 4 stocks.main:app -b 127.0.0.1:5000 -D
  - ps ax|grep gunicorn

script:
#  - pylint stocks/
  - flask --app=stocks.main:app  db upgrade --directory stocks/migrations
  - coverage run -m pytest && coverage report

after_script:
  - pkill gunicorn
  - ps ax|grep gunicorn

