language: python
python:
  - "3.8"
services:
  - mysql
env:
  - DB_NAME=my_stocks_db DB_USER=root DB_PASSWORD=password DB_HOST=l DB_PORT=5000 DB_URL=mysql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS my_stocks_db;'
  - gunicorn -w 4 wsgi:app -b localhost:5000 -D
  - ps ax|grep gunicorn

script:
#  - pylint stocks/
  - flask --app=stocks.main:app db upgrade --directory stocks/migrations
  - coverage run -m pytest && coverage report

after_script:
  - pkill gunicorn
  - ps ax|grep gunicorn

