"""Init migration.

Revision ID: 52b07bf1bcb8
Revises: 
Create Date: 2023-03-07 16:15:24.055217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52b07bf1bcb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index('company')

    op.drop_table('stocks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('phone')

    op.drop_table('users')
    op.drop_table('users_stocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_stocks',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='users_stocks_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_stocks_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'stock_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('stocks_amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('registration_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=False)

    op.create_table('stocks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sector', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index('company', ['company'], unique=False)

    # ### end Alembic commands ###
